### ISSUE TITLE
Is it possible to interpolate values for custom media?

### ISSUE THREAD

**Issue by comatory** [csstools/postcss-custom-media#61]
Is there a way to change this:

`@custom-media --small-viewport (max-width: 30em);`

to this?

`@custom-media --small-viewport (max-width: var(--my-custom-max-width));`

I'm creating a component library with provided stylesheets and expose variables, this would be better for code re-use.

**Comment by kuserich** [comment]
@comatory [Unfortunately, no](https://stackoverflow.com/a/40723269/2547325)

**Comment by comatory** [comment]
I see it's not possible with CSS spec. However could this be a feature of this plugin? Would it be possible to replace variables when given some source of those variables?

**Comment by jtomaszewski** [comment]
If it's not part of the CSS spec, which this plugin is trying to follow, then it shouldn't implement it.

However, I think it'd be suuuper nice if the plugin could catch definitions with `var(--` in it and warn about it in the dev console, that it won't work (possibly with a link to this issue to explain it).

**Comment by comatory** [comment]
> However, I think it'd be suuuper nice if the plugin could catch
> definitions with `var(--` in it and warn about it in the dev console,
> that it won't work (possibly with a link to this issue to explain it).

I agree.
